AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website on EC2.
  Kittens Carousel Static Website will be deployed on Amazon Linux 2 EC2 Instance with custom 
  security group which allows http connections on port 80 and ssh port 22 from anywhere. Kittens Carousel Static 
  Website is downloaded from my Public Github repository, then deployed on Apache Web Server.
  
Resources:
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01c647eace872fc02
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds: 
        - !Ref MySecGrp
      Tags: 
        - Key: Name
          Value: !Sub Yasin ${AWS::StackName}
      UserData:
        Fn::Base64: |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/ykartal2/101-kittens-carousel-static-website-ec2/main/101-kittens-carousel-static-website-ec2/static-web"
            cd /var/www/html
            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg
            wget ${FOLDER}/cat3.png
            systemctl start httpd
            systemctl enable httpd  
  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http # Required
      GroupName: yasinsecportfolio
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: env
          Value: dev 
Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName
